### ISSUE TITLE
Include build instructions? 

### ISSUE THREAD

**Issue by numin0us** [Ayrx/FindNativeJNIMethods#1]
Hi there, I've tried to build this file a few different ways and have been unable to do so.

```
root@kali:~/github/FindNativeJNIMethods# jar --create --file findNativeJNIMethods.jar
 --manifest src/META-INF/MANIFEST.MF -C src/             
root@kali:~/github/FindNativeJNIMethods# java -jar findNativeJNIMethods.jar 
Error: Could not find or load main class me.ayrx.Main                                
Caused by: java.lang.ClassNotFoundException: me.ayrx.Main
```

Is there something I am doing wrong? Let me know the appropriate way to build the JAR file.

**Comment by Ayrx** [comment]
Hey!

It's a pretty standard build with [IntelliJ](https://www.jetbrains.com/idea/download/) or any Java IDE. You can also find the pre-built JAR file in the [releases section](https://github.com/Ayrx/FindNativeJNIMethods/releases).

Do let me know if this doesn't solve your problem. Thanks!

**Comment by Ayrx** [comment]
_Annnnnd_ I just realized I didn't publish a release with the latest changes so I just did a 0.2 release with the latest JAR file uploaded.
