### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by allRiceOnMe** [Ayrx/FindNativeJNIMethods#2]
Hey!

First of all: Great tool and great blog post!!!

Version 0.2 works fine. But with version 0.3 I'm getting the following exception:

```
Exception in thread "main" java.lang.UnsupportedOperationException: ArgType.getObject(), call class: class jadx.core.dex.instructions.args.ArgType$ArrayArg
	at jadx.core.dex.instructions.args.ArgType.getObject(ArgType.java:438)
	at me.ayrx.Main.parseArgumentSignature(Main.java:81)
	at me.ayrx.Main.main(Main.java:48)
```

Maybe something about [this](https://github.com/skylot/jadx/blob/f228a72118c25ad530b7e816006d4f67ef732d33/jadx-core/src/main/java/jadx/core/dex/instructions/args/ArgType.java#L494) code inside of the `getObject()` method of the `ArgType` in jadx? You're calling this method [here](https://github.com/Ayrx/FindNativeJNIMethods/blob/6a001acc43ce0c44d1eb5a6dd8f626232a257616/src/me/ayrx/Main.java#L81).

Tested with following command:

```
$ java -jar FindNativeJNIMethods.jar UnCrackable-Level3.apk defs.json
```

**Comment by Ayrx** [comment]
Hi! Thanks for the report. I released v0.4 which should fix the bug which stemmed from the code not handling array types properly when parsing the argument signature.

Do let me know if you still face issues with the latest version.
